openapi: 3.0.0
info:
  title: HTT Token API
  version: "1.0.0"
  description: HTT Wallet, Booking, and Rewards API

paths:
  /v1/status:
    get:
      summary: Check API status
      responses:
        '200':
          description: Server is online

  /v1/wallet/balance/{address}:
    get:
      summary: Get HTT wallet balance
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Wallet balance returned

  /v1/rewards/claim:
    post:
      summary: Claim reward
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Reward claimed
  
    /v1/login:
    post:
      summary: Wallet login via MetaMask signature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                signature:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Wallet verified
        '401':
          description: Signature failed

